# Generated by Django 4.2.2 on 2023-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente', '0002_agent_apartament_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='varsta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='etaj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='metriPatrati',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='nrCamere',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='pret',
            field=models.IntegerField(),
        ),
    ]
